### ISSUE TITLE
download never works in my via browser 

### ISSUE THREAD

**Issue by vientito** [tuyafeng/Via#846]
downloading anything never really works

e.g.
http://www1.tvboxnow.com/attachment.php?aid=5239276&k=51b9cf495df389a7006daa458e061be9&t=1621017585&ck=e09d0830&sid=41c8tI4wsT9QfRwBHZgVrIKeqi6Mcc4k3TzADJbdOEFRnPs

This is one such example. The download clock will spin and at the end says download failed. Permission for storage is on.

Other browsers in my system work fine.

**Comment by tuyafeng** [comment]
This bug should have been fixed in version 4.2.8.

**Comment by vientito** [comment]
my version is exactly that but still not working. other browser works in my system

On June 13, 2021 11:48:46 p.m. EST, Yafeng ***@***.***> wrote:
>This bug should have been fixed in version 4.2.8.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tuyafeng/Via/issues/846#issuecomment-860359245

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
